In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [41]:
data = pd.read_csv('international-airline-passengers.csv')

In [42]:
plt.plot(data.passengers)
plt.show()

In [17]:
p = data.passengers

In [61]:
i=0
seq_X=[]
seq_Y=[]

while i+4<len(p):
    seq_X.append(p[i:i+5])
    seq_Y.append(p[5])
    i=i+1

In [62]:
X=np.array(seq_X)
Y=np.array(seq_Y)

In [63]:
print(X)
print(Y)

[[112. 118. 132. 129. 121.]
 [118. 132. 129. 121. 135.]
 [132. 129. 121. 135. 148.]
 [129. 121. 135. 148. 148.]
 [121. 135. 148. 148. 136.]
 [135. 148. 148. 136. 119.]
 [148. 148. 136. 119. 104.]
 [148. 136. 119. 104. 118.]
 [136. 119. 104. 118. 115.]
 [119. 104. 118. 115. 126.]
 [104. 118. 115. 126. 141.]
 [118. 115. 126. 141. 135.]
 [115. 126. 141. 135. 125.]
 [126. 141. 135. 125. 149.]
 [141. 135. 125. 149. 170.]
 [135. 125. 149. 170. 170.]
 [125. 149. 170. 170. 158.]
 [149. 170. 170. 158. 133.]
 [170. 170. 158. 133. 114.]
 [170. 158. 133. 114. 140.]
 [158. 133. 114. 140. 145.]
 [133. 114. 140. 145. 150.]
 [114. 140. 145. 150. 178.]
 [140. 145. 150. 178. 163.]
 [145. 150. 178. 163. 172.]
 [150. 178. 163. 172. 178.]
 [178. 163. 172. 178. 199.]
 [163. 172. 178. 199. 199.]
 [172. 178. 199. 199. 184.]
 [178. 199. 199. 184. 162.]
 [199. 199. 184. 162. 146.]
 [199. 184. 162. 146. 166.]
 [184. 162. 146. 166. 171.]
 [162. 146. 166. 171. 180.]
 [146. 166. 171. 180. 193.]
 [166. 171. 180. 193

In [64]:
X = np.reshape(X, (X.shape[0],1 ,X.shape[1]))

In [65]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM


In [66]:

# create the model
model = Sequential()
model.add(LSTM(4, input_shape=(1,5)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')


In [75]:
model.fit(X, Y, epochs=100, batch_size=1, verbose=2)
print(model.summary())


Epoch 1/100
 - 0s - loss: nan
Epoch 2/100
 - 0s - loss: nan
Epoch 3/100
 - 0s - loss: nan
Epoch 4/100
 - 0s - loss: nan
Epoch 5/100
 - 0s - loss: nan
Epoch 6/100
 - 0s - loss: nan
Epoch 7/100
 - 0s - loss: nan
Epoch 8/100
 - 0s - loss: nan
Epoch 9/100
 - 0s - loss: nan
Epoch 10/100
 - 0s - loss: nan
Epoch 11/100
 - 0s - loss: nan
Epoch 12/100
 - 0s - loss: nan
Epoch 13/100
 - 0s - loss: nan
Epoch 14/100
 - 0s - loss: nan
Epoch 15/100
 - 0s - loss: nan
Epoch 16/100
 - 0s - loss: nan
Epoch 17/100
 - 0s - loss: nan
Epoch 18/100
 - 0s - loss: nan
Epoch 19/100
 - 0s - loss: nan
Epoch 20/100
 - 0s - loss: nan
Epoch 21/100
 - 0s - loss: nan
Epoch 22/100
 - 0s - loss: nan
Epoch 23/100
 - 0s - loss: nan
Epoch 24/100
 - 0s - loss: nan
Epoch 25/100
 - 0s - loss: nan
Epoch 26/100
 - 0s - loss: nan
Epoch 27/100
 - 0s - loss: nan
Epoch 28/100
 - 0s - loss: nan
Epoch 29/100
 - 0s - loss: nan
Epoch 30/100
 - 0s - loss: nan
Epoch 31/100
 - 0s - loss: nan
Epoch 32/100
 - 0s - loss: nan
Epoch 33/100
 - 0